---
EnableDefaultLinters: true
linters:
  AllowedScriptType:
    enabled: true
  ClosingErbTagIndent:
    enabled: true
  ExtraNewline:
    enabled: true
  FinalNewline:
    enabled: true
  ParserErrors:
    enabled: false
  RightTrim:
    enabled: true
  SelfClosingTag:
    enabled: true
  SpaceAroundErbTag:
    enabled: true
  SpaceInHtmlTag:
    enabled: true
  TrailingWhitespace:
    enabled: true
  RequireInputAutocomplete:
    enabled: false
  RequireInputAutofocus:
    enabled: false
  RequireInputAutosave:
    enabled: false
  RequireInputList:
    enabled: false
  RequireInputMax:
    enabled: false
  RequireInputMin:
    enabled: false
  RequireInputPattern:
    enabled: false
  RequireInputStep:
    enabled: false
  RequireInputType:
    enabled: false
  RequireInputValue:
    enabled: false
  RequireInputAutocomplete:
    enabled: false
  RequireInputAutofocus:
    enabled: false
  RequireInputAutosave:
    enabled: false
  RequireInputList:
    enabled: false
  RequireInputMax:
    enabled: false
  RequireInputMin:
    enabled: false
  RequireInputPattern:
    enabled: false
  RequireInputStep:
    enabled: false
  RequireInputType:
    enabled: false
  RequireInputValue:
    enabled: false 