---
EnableDefaultLinters: true
linters:
  ClosingErbTagIndent:
    enabled: true
  ExtraNewline:
    enabled: true
  FinalNewline:
    enabled: true
  ParserErrors:
    enabled: true
  RightTrim:
    enabled: true
  SelfClosingTag:
    enabled: true
  SpaceAroundErbTag:
    enabled: true
  SpaceInHtmlTag:
    enabled: true 